export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';

export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';

export const GET_USERS_IN_PROGRESS = 'GET_USERS_IN_PROGRESS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';